Repository RasmusBrostroem/ConnectFourRL, pull requests merged in 2023-08, with the labels that each got.

#82 Refactor use game instance
  game/Env.py
  game/connectFour.py
  game/players.py
  test.py
Labels: bug, enhancement

#85 Implement td agent
  game/Env.py
  game/players.py
  td-testing.py
  td_agent_training_script.py
  test.py
Labels: enhancement

#90 74 let humanplayer interact with mouse input
  game/connectFour.py
  game/players.py
  test.py
Labels: enhancement

#106 Use any reward for update
  game/Env.py
  game/players.py
Labels: enhancement

#107 Epsilon-greedy action selection
  game/players.py
Labels: enhancement

#110 Move definition of `calculate_rewards()`
  game/players.py
Labels: refactor

#112 Clean connect_four
  game/connectFour.py
Labels: documentation
